import { Demo } from "@/components/demo";
import { Wallet } from "@/components/wallet";
import { useIsMounted } from "@/hooks/useIsMounted";
import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import { useAccount } from "wagmi";

import dynamic from "next/dynamic";
import { PostGreenfield } from "@/components/greenfield";
import { Breadcrumb } from "@/components/breadcrumb";
import { useRouter } from "next/router";

let Editor = dynamic(() => import("@/components/editor"), {
  ssr: false,
});

const inter = Inter({ subsets: ["latin"] });

export default function CreateNewPost() {
  const isMounted = useIsMounted();
  const { isConnected } = useAccount();
  const [content, setContent] = useState<any>({});
  // const editorRef = useRef(null);
  const router = useRouter();

  const info = {
    bucketName: router.query.bucket,
    objectName: "",
    postTitle: "",
  }

  if (!isMounted) return null;

  return (
    <>
      <Head>
        <title>Editor Greenfield App</title>
        <meta name="description" content="Generated by create Greenfield app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Wallet />
        {isConnected && (
          <>
            <Breadcrumb />
            <PostGreenfield data={content} objectInfo={info}>
              <Editor
                data={content}
                onChange={(e) => {
                  setContent({ ...content, payload: e });
                }}
                holder="editor_create"
              // editorRef={editorRef}
              />
            </PostGreenfield>
          </>
        )}
      </main>
    </>
  );
}
