import { Breadcrumb } from "@/components/breadcrumb";
import { WebsitesDashboard } from "@/components/dashboard";
import { Wallet } from "@/components/wallet";
import { useIsMounted } from "@/hooks/useIsMounted";
import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import { useAccount } from "wagmi";

const inter = Inter({ subsets: ["latin"] });

export default function DashboardPage() {
  const isMounted = useIsMounted();
  const { isConnected } = useAccount();
  const [content, setContent] = useState("");
  const editorRef = useRef(null);

  if (!isMounted) return null;

  return (
    <>
      <Head>
        <title>Greenfield Blog dApp</title>
        <meta name="description" content="Generated by create Greenfield app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Wallet />
        <Breadcrumb />
        {isConnected && (
          <>
            <WebsitesDashboard />
          </>
        )}
      </main>
    </>
  );
}
