import { Breadcrumb } from "@/components/breadcrumb";
import { Dashboard } from "@/components/dashboard";
import { Demo } from "@/components/demo";
import { Wallet } from "@/components/wallet";
import { useIsMounted } from "@/hooks/useIsMounted";
import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useRef, useState } from "react";
import { useAccount } from "wagmi";

const inter = Inter({ subsets: ["latin"] });

export default function DashboardPage() {
  const isMounted = useIsMounted();
  const { isConnected } = useAccount();
  const [content, setContent] = useState("");
  const editorRef = useRef(null);
  const router = useRouter();

  if (!isMounted) return null;

  return (
    <>
      <Head>
        <title>Editor Greenfield App</title>
        <meta name="description" content="Generated by create Greenfield app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Wallet />
        <Breadcrumb />
        {isConnected && (
          <>
            <Dashboard bucket={router.query.bucket} />
          </>
        )}
      </main>
    </>
  );
}
